"""The ledger: an append-only record of every change made to the data.

Most cleaning tools give you a ledger you can *read*. This one you can *re-run*.

`to_script()` emits a standalone Python file that reproduces the entire
cleaning session from the raw input — no HayMedics Data Analyser, no LLM, no
API key, no network. Hand it to a reviewer and they can verify your work.
Commit it next to your paper and your cleaning is reproducible three years
from now when this app no longer exists.

That's the difference between a tool that cleans your data and a tool that
survives peer review.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime

import pandas as pd

from .ops import REGISTRY


@dataclass
class Entry:
    seq: int
    op: str
    params: dict
    rationale: str
    rows_before: int
    rows_after: int
    cols_before: int
    cols_after: int
    stats: dict = field(default_factory=dict)
    timestamp: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat(timespec="seconds")
    )

    @property
    def summary(self) -> str:
        affected = self.stats.get("rows_affected", 0)
        return f"{self.op} — {affected} rows affected"


class Ledger:
    """Applies operations and remembers exactly what it did."""

    def __init__(self, source_name: str = "raw.csv") -> None:
        self.source_name = source_name
        self.entries: list[Entry] = []
        self._snapshots: list[pd.DataFrame] = []

    def __len__(self) -> int:
        return len(self.entries)

    def apply(
        self,
        df: pd.DataFrame,
        op_name: str,
        params: dict | None = None,
        rationale: str = "",
    ) -> pd.DataFrame:
        """Run one operation, record it, return the new frame.

        Raises KeyError if the op isn't registered. That's deliberate: an LLM
        (or anything else) can only ever reach ops we shipped on purpose.
        """
        params = dict(params or {})
        if op_name not in REGISTRY:
            raise KeyError(
                f"Unknown operation {op_name!r}. Registered: {sorted(REGISTRY)}"
            )

        operation = REGISTRY[op_name]
        self._snapshots.append(df.copy())

        rows_before, cols_before = df.shape
        new_df, stats = operation.apply(df, **params)
        rows_after, cols_after = new_df.shape

        self.entries.append(
            Entry(
                seq=len(self.entries) + 1,
                op=op_name,
                params=params,
                rationale=rationale,
                rows_before=rows_before,
                rows_after=rows_after,
                cols_before=cols_before,
                cols_after=cols_after,
                stats={k: _jsonable(v) for k, v in stats.items()},
            )
        )
        return new_df

    def undo(self) -> pd.DataFrame | None:
        """Step back one operation. The original has no undo."""
        if not self._snapshots:
            return None
        self.entries.pop()
        return self._snapshots.pop()

    def to_dataframe(self) -> pd.DataFrame:
        """The ledger as a table, for display in the UI."""
        if not self.entries:
            return pd.DataFrame(
                columns=["#", "Operation", "Rows affected", "Shape", "Why"]
            )
        return pd.DataFrame(
            [
                {
                    "#": e.seq,
                    "Operation": e.op,
                    "Rows affected": e.stats.get("rows_affected", 0),
                    "Shape": f"{e.rows_before}x{e.cols_before} -> {e.rows_after}x{e.cols_after}",
                    "Why": e.rationale or "—",
                }
                for e in self.entries
            ]
        )

    def to_json(self) -> str:
        return json.dumps(
            {"source": self.source_name, "entries": [asdict(e) for e in self.entries]},
            indent=2,
            default=str,
        )

    def to_script(self) -> str:
        """Render the session as a standalone, runnable Python script.

        This is the whole point of the project. Every op carries its own code
        renderer next to its runner, so this can't drift from what executed.
        """
        stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        needs_hashlib = any(
            e.op == "deidentify" and e.params.get("method", "hash") == "hash"
            for e in self.entries
        )

        lines = [
            '"""Cleaning script generated by HayMedics Data Analyser.',
            "",
            f"Source:    {self.source_name}",
            f"Generated: {stamp}",
            f"Steps:     {len(self.entries)}",
            "",
            "This reproduces the cleaning session exactly. It needs pandas and",
            "nothing else — no HayMedics Data Analyser, no API key, no network. Run it, diff the",
            "output against the cleaned file you downloaded, and they will match.",
            '"""',
            "",
            "import pandas as pd",
        ]
        if needs_hashlib:
            lines.append("import hashlib")

        lines += [
            "",
            f"df = pd.read_csv({self.source_name!r})",
            "print(f'Loaded {len(df):,} rows x {len(df.columns)} columns')",
            "",
        ]

        if not self.entries:
            lines.append("# No cleaning operations were recorded.")
        for entry in self.entries:
            operation = REGISTRY[entry.op]
            affected = entry.stats.get("rows_affected", 0)

            lines.append(
                f"# [{entry.seq}] {entry.op} — {affected} rows affected "
                f"({entry.rows_before}x{entry.cols_before} -> "
                f"{entry.rows_after}x{entry.cols_after})"
            )
            if entry.rationale:
                for wrapped in _wrap(entry.rationale, 72):
                    lines.append(f"#      {wrapped}")

            try:
                rendered = operation.code(**entry.params)
            except Exception as exc:  # pragma: no cover - renderer bug guard
                rendered = f"# !! could not render this step: {exc}"
            lines.append(rendered)
            lines.append("")

        lines += [
            "df.to_csv('cleaned.csv', index=False)",
            "print(f'Wrote cleaned.csv — {len(df):,} rows x {len(df.columns)} columns')",
            "",
        ]
        return "\n".join(lines)


def _wrap(text: str, width: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines


def _jsonable(value: object) -> object:
    if isinstance(value, (pd.Timestamp, pd.Timedelta)):
        return str(value)
    if hasattr(value, "item"):
        try:
            return value.item()
        except (ValueError, AttributeError):
            return str(value)
    return value
